replicaCount: 1

image:
  repository: ghcr.io/raunoproekspert/micro-services-demo/stock-service
  tag: "sha-61369088f6111deaf5ed272f38195c386be5d376"
  pullPolicy: Always

imagePullSecret: ghcr-pull-secret

service:
  type: ClusterIP
  port: 8082

ingress:
  enabled: true
  host: stock-service.local

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

livenessProbe:
  httpGet:
    path: /health
    port: 8082
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /health
    port: 8082
  initialDelaySeconds: 5
  periodSeconds: 10
